In [24]:
import torch

x = torch.tensor([1,2])
y = torch.tensor([3,4])

id_before = id(y)
y = y+x
print(id_before)
print(id(y))

1818645353240
1818645263488


In [ ]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
# 索引 [:]写进y对应的内存中
y[:] = y + x
print(id(y) == id_before) # True

## Tensor转NumPy

In [30]:
a = torch.ones(5)
b = a.numpy()
print(a,b)

a+= 1
print(a,b)
b+=1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


## NumPy数组转Tensor

In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)
a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## torch.tensor() 不再共享内存

In [38]:
c = torch.tensor(a)
a += 1
print(a, c)

[5. 5. 5. 5. 5.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


In [45]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型