In [7]:
import torch
# 创建一个5x3的随机初始化的Tensor
x= torch.rand(5,3)
print(x)

tensor([[0.5493, 0.9475, 0.8494],
        [0.3884, 0.3638, 0.5520],
        [0.5746, 0.8004, 0.0243],
        [0.9716, 0.7262, 0.9421],
        [0.2689, 0.3665, 0.1231]])


In [6]:
# x = torch.zeros(5,5,dtype=torch.long)
print(x)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [14]:
x = torch.tensor([5.5,3])
print(x)
print(x.size())
print(x.shape)

tensor([5.5000, 3.0000])
torch.Size([2])
torch.Size([2])


In [38]:
y = torch.ones(5,2)

print(torch.add(x,y))

tensor([[6.5000, 4.0000],
        [6.5000, 4.0000],
        [6.5000, 4.0000],
        [6.5000, 4.0000],
        [6.5000, 4.0000]])


In [46]:
# 使用view()来改变tensor的形状
x= torch.rand(5,3)
y = x.view(15)
z = x.view(-1,5)
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [50]:
# view()返回的新tensor 与源tensor 虽然有size 但是共享data的
x +=1
print(x)
print(y)

tensor([[4.5255, 4.2676, 4.6972],
        [4.0892, 4.5118, 4.6477],
        [4.7410, 4.1846, 4.5145],
        [4.6359, 4.2657, 4.0469],
        [4.8460, 4.5593, 4.2873]])
tensor([4.5255, 4.2676, 4.6972, 4.0892, 4.5118, 4.6477, 4.7410, 4.1846, 4.5145,
        4.6359, 4.2657, 4.0469, 4.8460, 4.5593, 4.2873])


In [119]:
# 线性代数
x= torch.rand(5,5)
# 深拷贝
s = x.clone().view(25)
print(x)
print(x.trace())
print(x.diag())
print(x.triu())
print(x.tril())


tensor([[0.0930, 0.6679, 0.2801, 0.8255, 0.0232],
        [0.2363, 0.4651, 0.3265, 0.4988, 0.2038],
        [0.3638, 0.7642, 0.0977, 0.9063, 0.8566],
        [0.5530, 0.5119, 0.1694, 0.1437, 0.5428],
        [0.1320, 0.4998, 0.7651, 0.2328, 0.8069]])
tensor(1.6065)
tensor([0.0930, 0.4651, 0.0977, 0.1437, 0.8069])
tensor([[0.0930, 0.6679, 0.2801, 0.8255, 0.0232],
        [0.0000, 0.4651, 0.3265, 0.4988, 0.2038],
        [0.0000, 0.0000, 0.0977, 0.9063, 0.8566],
        [0.0000, 0.0000, 0.0000, 0.1437, 0.5428],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.8069]])
tensor([[0.0930, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2363, 0.4651, 0.0000, 0.0000, 0.0000],
        [0.3638, 0.7642, 0.0977, 0.0000, 0.0000],
        [0.5530, 0.5119, 0.1694, 0.1437, 0.0000],
        [0.1320, 0.4998, 0.7651, 0.2328, 0.8069]])
